"""
RunbookService — generates operational runbooks from investigations (1 Gemini call).

Triggered only when the user explicitly clicks "Generate Runbook" — never automatic.
The generated runbook is saved as a document and indexed into Qdrant so future
investigations can retrieve it as evidence.

This makes OpsLens self-improving: every investigation can contribute a runbook
that helps diagnose the same issue faster next time.
"""

import time
from datetime import datetime

from google import genai
from sqlalchemy.orm import Session

from app.config.settings import settings
from app.core.logging import get_logger
from app.core.token_tracker import track_usage

logger = get_logger(__name__)


class RunbookService:

    def __init__(self, db: Session):
        self.db = db
        self.client = genai.Client(api_key=settings.gemini_api_key)
        self.model = settings.gemini_model

    def generate_runbook(
        self,
        investigation: dict,
        incident_title: str,
        service: str,
        organization_id: int,
        user_id: int,
    ) -> dict:
        """
        Generate a structured operational runbook from an investigation report.

        The runbook is:
          1. Generated by Gemini (1 LLM call)
          2. Saved as a .txt document
          3. Automatically indexed into Qdrant

        Future investigations on the same service will retrieve this runbook
        as evidence, increasing confidence scores.

        Args:
            investigation: The full investigation report dict.
            incident_title: The incident title for the runbook filename.
            service: The affected service name.
            organization_id: The org to save the document under.
            user_id: The user triggering the generation.

        Returns:
            {"runbook_text": "...", "document_id": N, "chunks_indexed": N}
        """
        start = time.monotonic()
        logger.info(
            "Runbook generation started: service=%s org_id=%d",
            service,
            organization_id,
        )

        root_cause = investigation.get("root_cause", "")
        root_cause_status = investigation.get("root_cause_status", "Likely")
        immediate_actions = investigation.get("immediate_actions", [])
        long_term_prevention = investigation.get("long_term_prevention", [])
        alternative_hypotheses = investigation.get("alternative_hypotheses", [])
        confidence = investigation.get("confidence", 0)

        actions_text = "\n".join(f"- {a}" for a in immediate_actions) if immediate_actions else "- See investigation report"
        prevention_text = "\n".join(f"- {p}" for p in long_term_prevention) if long_term_prevention else "- See investigation report"
        hypotheses_text = "\n".join(
            f"- {h.get('hypothesis', '')} (confidence: {h.get('confidence_pct', 0)}%)"
            for h in alternative_hypotheses
        ) if alternative_hypotheses else "- None documented"

        prompt = f"""You are a Senior SRE creating an operational runbook for the engineering team.

Based on this incident investigation, create a structured runbook that engineers can follow
the next time this issue occurs on the {service} service.

INVESTIGATION SUMMARY:
Service: {service}
Root Cause Status: {root_cause_status}
Root Cause: {root_cause}
Confidence: {confidence}%

Immediate Actions Taken:
{actions_text}

Alternative Hypotheses Considered:
{hypotheses_text}

Write a runbook with these EXACT sections:

# Runbook: {incident_title} — {service}
Generated: {datetime.now().strftime("%Y-%m-%d")}

## Overview
What this runbook covers and when to use it.

## Symptoms
List the specific symptoms that indicate this issue.

## Prerequisites
What access, tools, or permissions you need before starting.

## Diagnosis Steps
Numbered steps to confirm this is the issue (with exact commands).

## Remediation Steps
Numbered steps to fix it (with exact commands).

## Rollback Steps
How to safely rollback if remediation makes things worse.

## Prevention
From the investigation: {prevention_text}

## Related Incidents
Note that this runbook was generated from a previous investigation.
Engineers should check the OpsLens investigation history for similar incidents.

Write the runbook in plain text, not markdown code blocks.
Be specific with commands. Use placeholder values like <namespace>, <pod-name> where needed.
"""

        response = self.client.models.generate_content(
            model=self.model,
            contents=prompt,
        )
        track_usage(response, operation="runbook_generation", model=self.model)

        runbook_text = response.text or ""
        elapsed = round(time.monotonic() - start, 2)

        logger.info(
            "Runbook generated: service=%s length=%d elapsed=%.2fs",
            service,
            len(runbook_text),
            elapsed,
        )

        # Save and index the runbook as a document
        document_id = None
        chunks_indexed = 0
        try:
            document_id, chunks_indexed = self._save_and_index(
                runbook_text=runbook_text,
                incident_title=incident_title,
                service=service,
                organization_id=organization_id,
                user_id=user_id,
            )
            logger.info(
                "Runbook indexed: document_id=%d chunks=%d",
                document_id,
                chunks_indexed,
            )
        except Exception as exc:
            logger.error("Failed to index runbook: %s", exc, exc_info=True)

        return {
            "runbook_text": runbook_text,
            "document_id": document_id,
            "chunks_indexed": chunks_indexed,
        }

    def _save_and_index(
        self,
        runbook_text: str,
        incident_title: str,
        service: str,
        organization_id: int,
        user_id: int,
    ) -> tuple[int, int]:
        """Save runbook as a .txt file and index it into Qdrant."""
        import os
        import uuid

        from app.models.document import Document, IndexStatus
        from app.repositories.document_repository import DocumentRepository
        from app.services.indexing_service import IndexingService

        safe_title = "".join(c if c.isalnum() or c in " -_" else "_" for c in incident_title)[:50]
        filename = f"runbook_{service}_{safe_title}_{uuid.uuid4().hex[:8]}.txt"
        storage_path = os.path.join(settings.upload_dir, filename)

        os.makedirs(settings.upload_dir, exist_ok=True)
        with open(storage_path, "w", encoding="utf-8") as f:
            f.write(runbook_text)

        repo = DocumentRepository(self.db)
        document = repo.create(
            Document(
                filename=filename,
                original_filename=f"[AUTO] Runbook: {incident_title[:60]}.txt",
                content_type="text/plain",
                file_size=len(runbook_text.encode()),
                storage_path=storage_path,
                organization_id=organization_id,
                uploaded_by=user_id,
                index_status=IndexStatus.PENDING,
            )
        )

        chunks_indexed = IndexingService(db=self.db).index_document(document)
        return document.id, chunks_indexed
