"""add user fields

Revision ID: 146b903e554c
Revises: ce8ba29c4164
Create Date: 2026-06-26 21:00:03.475778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146b903e554c'
down_revision: Union[str, Sequence[str], None] = 'ce8ba29c4164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'role')
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.drop_column('organizations', 'created_at')
    # ### end Alembic commands ###
