/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestigateIndexRouteImport } from './routes/investigate.index'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as InvestigateIncident_idRouteImport } from './routes/investigate.$incident_id'
import { Route as HistoryInvestigation_idRouteImport } from './routes/history.$investigation_id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigateIndexRoute = InvestigateIndexRouteImport.update({
  id: '/investigate/',
  path: '/investigate/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigateIncident_idRoute = InvestigateIncident_idRouteImport.update({
  id: '/investigate/$incident_id',
  path: '/investigate/$incident_id',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryInvestigation_idRoute = HistoryInvestigation_idRouteImport.update({
  id: '/history/$investigation_id',
  path: '/history/$investigation_id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/incidents': typeof IncidentsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/history/$investigation_id': typeof HistoryInvestigation_idRoute
  '/investigate/$incident_id': typeof InvestigateIncident_idRoute
  '/history/': typeof HistoryIndexRoute
  '/investigate/': typeof InvestigateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/incidents': typeof IncidentsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/history/$investigation_id': typeof HistoryInvestigation_idRoute
  '/investigate/$incident_id': typeof InvestigateIncident_idRoute
  '/history': typeof HistoryIndexRoute
  '/investigate': typeof InvestigateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/incidents': typeof IncidentsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/history/$investigation_id': typeof HistoryInvestigation_idRoute
  '/investigate/$incident_id': typeof InvestigateIncident_idRoute
  '/history/': typeof HistoryIndexRoute
  '/investigate/': typeof InvestigateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/incidents'
    | '/login'
    | '/register'
    | '/settings'
    | '/history/$investigation_id'
    | '/investigate/$incident_id'
    | '/history/'
    | '/investigate/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/incidents'
    | '/login'
    | '/register'
    | '/settings'
    | '/history/$investigation_id'
    | '/investigate/$incident_id'
    | '/history'
    | '/investigate'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/incidents'
    | '/login'
    | '/register'
    | '/settings'
    | '/history/$investigation_id'
    | '/investigate/$incident_id'
    | '/history/'
    | '/investigate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  IncidentsRoute: typeof IncidentsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  HistoryInvestigation_idRoute: typeof HistoryInvestigation_idRoute
  InvestigateIncident_idRoute: typeof InvestigateIncident_idRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  InvestigateIndexRoute: typeof InvestigateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigate/': {
      id: '/investigate/'
      path: '/investigate'
      fullPath: '/investigate/'
      preLoaderRoute: typeof InvestigateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigate/$incident_id': {
      id: '/investigate/$incident_id'
      path: '/investigate/$incident_id'
      fullPath: '/investigate/$incident_id'
      preLoaderRoute: typeof InvestigateIncident_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$investigation_id': {
      id: '/history/$investigation_id'
      path: '/history/$investigation_id'
      fullPath: '/history/$investigation_id'
      preLoaderRoute: typeof HistoryInvestigation_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  IncidentsRoute: IncidentsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  HistoryInvestigation_idRoute: HistoryInvestigation_idRoute,
  InvestigateIncident_idRoute: InvestigateIncident_idRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  InvestigateIndexRoute: InvestigateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
